import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

import { Sidebar } from '@/components/Sidebar';
import { Button } from '@/components/ui/button';
import { Search, History, Zap, Home, User, Bell } from 'lucide-react';
import Link from 'next/link';
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={cn("scroll-smooth dark", "font-sans", inter.variable)}>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased selection:bg-primary selection:text-primary-foreground min-h-screen bg-background text-foreground overflow-x-hidden`}>
                <div className="max-w-[1400px] mx-auto w-full flex min-h-screen relative">
                    <div className="hidden md:block w-[280px] shrink-0 sticky top-0 h-screen">
                        <Sidebar />
                    </div>

                    <main className="flex-1 min-w-0">
                        <div className="max-w-4xl mx-auto px-6 md:px-12 py-12 md:py-20">
                            {children}
                        </div>
                    </main>
                </div>

                {/* Mobile Bottom Nav - Refined to match Industrial theme */}
                <div className="fixed bottom-0 left-0 right-0 z-50 md:hidden bg-background/95 backdrop-blur-md border-t border-border/10 flex items-center justify-around py-4 px-6">
                    <Link href="/"><Home className="h-5 w-5 text-foreground hover:text-primary transition-colors" /></Link>
                    <Link href="/explore"><Search className="h-5 w-5 text-muted-foreground/30 hover:text-primary transition-colors" /></Link>
                    <div className="h-11 w-11 bg-primary flex items-center justify-center -translate-y-4 border border-border/10 shadow-lg shadow-primary/20">
                        <Zap className="h-5 w-5 text-primary-foreground fill-current" />
                    </div>
                    <Link href="/notifications"><Bell className="h-5 w-5 text-muted-foreground/30 hover:text-primary transition-colors" /></Link>
                    <Link href="/profile"><User className="h-5 w-5 text-muted-foreground/30 hover:text-primary transition-colors" /></Link>
                </div>
            </body>
        </html>
    );
}

function TrendItem({ title, subtitle, count }: any) {
    return (
        <div className="hover:bg-muted/30 flex flex-col cursor-pointer transition-colors -mx-4 px-4 py-2 group">
            <div className="flex items-center justify-between">
                <span className="text-xs text-muted-foreground font-medium uppercase tracking-tight">{subtitle}</span>
                <History className="h-4 w-4 text-muted-foreground opacity-0 group-hover:opacity-100 transition-opacity" />
            </div>
            <span className="font-bold text-sm tracking-tight">{title}</span>
            <span className="text-xs text-muted-foreground font-medium">{count}</span>
        </div>
    );
}

function FollowItem({ name, handle }: any) {
    return (
        <div className="flex items-center justify-between gap-3 group -mx-2 px-2 py-2 hover:bg-muted/30 rounded-xl transition-colors cursor-pointer">
            <div className="flex items-center gap-3">
                <div className="h-10 w-10 bg-linear-to-br from-primary/30 to-primary/10 rounded-full flex items-center justify-center font-bold text-primary">
                    {name.charAt(0)}
                </div>
                <div className="flex flex-col max-w-[120px]">
                    <span className="font-bold text-sm truncate">{name}</span>
                    <span className="text-xs text-muted-foreground truncate">{handle}</span>
                </div>
            </div>
            <Button size="sm" className="rounded-full font-bold bg-foreground text-background hover:bg-foreground/90 h-8 px-4">Follow</Button>
        </div>
    );
}
